title: W Produções
description: >
  Casamento é sagrado

baseurl: "" 
url: "https://www.wproducoesdeeventos.com.br/" 

permalink: pretty

collections:
  material:
    output: true
    permalink: /material/:path

# Build settings
markdown: kramdown

