backend:
  name: github
  repo: w-produtora/w-produtora.github.io
  branch: master
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow

media_folder: "img/uploads"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Artigos" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagem do cabeçalho", name: "img", widget: "image"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Homepage", name: "tipo", widget: "boolean", required: false}
      - {label: "Tag", name: "tag", widget: "select", options: ["Dicas", "Opinião", "Portfolio"]}
      - {label: "Link da Call to Action", name: "linkcta", widget: "string"}
      - {label: "Call to Action", name: "cta", widget: "string"}
      - {label: "Categoria", name: "category", widget: "select", multiple: true, options: ["portfolio", "artigos"]}
      - {label: "link", name: "permalink", widget: "string"}
      - {label: "Resumo", name: "meta", widget: "text"}
      - {label: "Post", name: "body", widget: "markdown"}
  - name: "material" # Used in routes, e.g., /admin/collections/blog
    label: "Materiais de Apoio" # Used in the UI
    folder: "_material" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagem do cabeçalho", name: "img", widget: "image"}
      - {label: "Link da Call to Action", name: "linkcta", widget: "string"}
      - {label: "Call to Action", name: "cta", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
  - name: "casamento-sagrado"
    label: "Casamento é Sagrado"
    folder: "casamento-sagrado"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagem do cabeçalho", name: "img", widget: "hidden"}
      - {label: "Link da Call to Action", name: "linkcta", widget: "string"}
      - {label: "Call to Action", name: "cta", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}
      